config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :controllers => { sessions: 'sessions'}

  root to: 'home#index'

  namespace :admin do
    resources :dashboard, only: :index

    resources :orders do
      collection do
        get :get_quote
        get :update_maker_model
        get :update_items
        get :get_prev_item
        get :get_next_item
        get :autocomplete
      end
    end

    resources :skus

    resources :audits do
      collection do
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
      end
    end

    resources :purchase_orders do
      collection do
        get :get_states
        get :get_cities
        get :get_vendor_details
        get :get_warehouse_details
        post :clone_with_item
        post :clone
        post :add_to_inventory
        get :get_prev_item
        get :get_next_item
        get :get_tax_details
      end
    end

    resources :reports do
      collection do
        get :convert
        get :pdf
      end
    end

    # === Settings ===
    resources :devices
    resources :categories
    resources :makers
    resources :statuses
    resources :order_statuses
    resources :condition_types
    resources :grades
    resources :payment_methods
    resources :delivery_methods
    resources :delivery_types
    resources :customer_types
    resources :terms
    resources :departments
    resources :product_warranties
    resources :product_types
    resources :taxes do
      collection do
        get :get_states
      end
    end
    # === Settings ===

    #  === People ===
    resources :users
    resources :vendors do
      collection do
        get :get_states
        get :get_cities
      end
    end
    # resources :companies do
    #   collection do
    #     get :get_states
    #     get :get_cities
    #   end
    # end
    resources :customers do
      collection do
        get :get_states
        get :get_cities
        get :get_taxes
      end
    end
    #  === People ===

    resources :warehouses do
      collection do
        get :get_states
        get :get_cities
      end
    end

    resources :items do
      collection do
        get :update_maker_model
        get :update_sub_category
        get :set_device
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
        get :editable
        get :barcodes
        get :edit_all
        get :get_subcategories
        get :get_makermodels
      end
    end

    resources :quotes do
      collection do
        get :get_customer_details
        get :get_item_details
        get :update_models
        get :update_items
        get :get_states
        get :get_cities
        get :get_states_customer
        get :get_cities_customer
        get :get_tax_details
        get :send_email
        get :approve_quote
        get :get_prev_item
        get :get_next_item
      end
    end

    resources :import_data
    resources :tutorial, only: :index

  end

end

app/models/product_warranty.rb
class ProductWarranty < ApplicationRecord
  has_many :quotes
  has_many :quote_items
end

app/controllers/admin/product_warranties_controller.rb
class Admin::ProductWarrantiesController < AdminController
  before_action :set_id, :only=> [:show, :edit, :update, :destroy]

  def index
    @product_warranties = ProductWarranty.all.order('name ASC')
  end

  def new
    @product_warranty = ProductWarranty.new
  end

  def create
    @product_warranty = ProductWarranty.create(product_warranty_params)

    if @product_warranty.save
      redirect_to admin_product_warranties_path, notice: "Product Warranty was successfully added"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product_warranty.update(product_warranty_params)
      redirect_to admin_product_warranties_path, notice: "Product Warranty was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @product_warranty = ProductWarranty.find(params[:id])
    if @product_warranty.destroy
      message = "Product Warranty destroyed successfully"
    else
      message = "Product Warranty could not be destroyed"
    end
    respond_to do |format|
      format.html { redirect_to admin_product_warranties_path, :notice => message }
      format.json { head :ok }
    end
  end

  private

  def set_id
    @product_warranty = ProductWarranty.find(params[:id])
  end

  def product_warranty_params
    params.require(:product_warranty).permit(:name)
  end

end

app/views/admin/product_warranties/_form.html.haml
- if @product_warranty.errors
  - @product_warranty.errors.full_messages.each do |msg|
    .alert.alert-danger#error-msg
      = msg

= form_for([:admin, @product_warranty]) do |f|
  .form-group.row
    %label.col-sm-2.col-form-label Name
    .col-sm-10
      = f.text_field :name, class: 'form-control', required: true


  .form-group.row
    .col-sm-12
      .float-right
        %a.btn.btn-white.btn-sm{href: "/admin/product_warranties"} Cancel
        %button.btn.btn-primary.btn-sm{:warranty => "submit"} Save

app/views/admin/product_warranties/edit.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Update Product Warranties
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/product_warranties"} List View
      %li.breadcrumb-item.active
        %strong Edit
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Product Warranties Form
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up

        .ibox-content
          = render "form"

app/views/admin/product_warranties/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    %h2 Product Warranties
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/dashboard"} Dashboard
      %li.breadcrumb-item.active
        %strong List View
  .col-lg-4
    .clearfix-big
    .float-right
      %a.btn.btn-primary.mr-3{href: '/admin/product_warranties/new'}
        %i.fa.fa-plus
        Add Warranty


.wrapper.wrapper-content
  - if flash.present?
    .row
      .col-lg-12
        - flash.each do |name, msg|
          = content_tag :div, msg, class: "alert alert-info"
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Product Warranties Table
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up


        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-hover#product_warranty_dt
              %thead
                %tr
                  %th #
                  %th Name
                  %th{width: "15%"}
              %tbody
                - @product_warranties.each do |product_warranty|
                  %tr
                    %td= product_warranty.id
                    %td= product_warranty.name
                    %td.text-center
                      %a.btn.btn-xs{href: "/admin/product_warranties/#{product_warranty.id}/edit"}
                        %i.far.fa-edit
                      %a.btn.btn-xs{href: "/admin/product_warranties/#{product_warranty.id}"}
                        %i.far.fa-eye
                      = link_to "<i class='fas fa-trash-alt'></i>".html_safe, admin_product_warranty_path(product_warranty.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn code-red btn-xs'


:javascript
  $( document ).ready(function() {
    $('#product_warranty_dt').DataTable();
  });

app/views/admin/product_warranties/new.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Create Product Warranty
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/product_warranties"} List View
      %li.breadcrumb-item.active
        %strong New
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Product Warranty Form
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up

        .ibox-content
          = render "form"

app/views/admin/product_warranties/show.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Product Warranty Details
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/product_warranties"} List View
      %li.breadcrumb-item.active
        %strong Show
  .col-lg-2


.wrapper.wrapper-content
  .row
    .col-lg-12
      .ibox-content.m-b-sm.border-bottom
        .p-xs
          .float-left.m-r-md
            %i.fa.fa-info-circle.text-navy.mid-icon.mr-5
          %h2= @product_warranty.name
          %span= "ID: # #{@product_warranty.id}"