config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :controllers => { sessions: 'sessions'}

  root to: 'home#index'

  namespace :admin do
    resources :dashboard, only: :index

    resources :orders do
      collection do
        get :get_quote
        get :update_maker_model
        get :update_items
        get :get_prev_item
        get :get_next_item
        get :autocomplete
      end
    end

    resources :skus

    resources :audits do
      collection do
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
      end
    end

    resources :purchase_orders do
      collection do
        get :get_states
        get :get_cities
        get :get_vendor_details
        get :get_warehouse_details
        post :clone_with_item
        post :clone
        post :add_to_inventory
        get :get_prev_item
        get :get_next_item
        get :get_tax_details
      end
    end

    resources :reports do
      collection do
        get :convert
        get :pdf
      end
    end

    # === Settings ===
    resources :devices
    resources :categories
    resources :makers
    resources :statuses
    resources :order_statuses
    resources :condition_types
    resources :grades
    resources :payment_methods
    resources :delivery_methods
    resources :delivery_types
    resources :customer_types
    resources :terms
    resources :departments
    resources :product_warranties
    resources :product_types
    resources :taxes do
      collection do
        get :get_states
      end
    end
    # === Settings ===

    #  === People ===
    resources :users
    resources :vendors do
      collection do
        get :get_states
        get :get_cities
      end
    end
    # resources :companies do
    #   collection do
    #     get :get_states
    #     get :get_cities
    #   end
    # end
    resources :customers do
      collection do
        get :get_states
        get :get_cities
        get :get_taxes
      end
    end
    #  === People ===

    resources :warehouses do
      collection do
        get :get_states
        get :get_cities
      end
    end

    resources :items do
      collection do
        get :update_maker_model
        get :update_sub_category
        get :set_device
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
        get :editable
        get :barcodes
        get :edit_all
        get :get_subcategories
        get :get_makermodels
      end
    end

    resources :quotes do
      collection do
        get :get_customer_details
        get :get_item_details
        get :update_models
        get :update_items
        get :get_states
        get :get_cities
        get :get_states_customer
        get :get_cities_customer
        get :get_tax_details
        get :send_email
        get :approve_quote
        get :get_prev_item
        get :get_next_item
      end
    end

    resources :import_data
    resources :tutorial, only: :index

  end

end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :items
  has_many :quote_items
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :delivery_method, optional: true
  belongs_to :delivery_type, optional: true
  belongs_to :quote
  belongs_to :order_status
  has_many :order_items
  accepts_nested_attributes_for :order_items, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_id, :only=> [:show, :edit, :update, :destroy]
  before_action :load_data, :only=> [:new, :create, :edit, :update]

  def index
    @orders = Order.all.order("id DESC") if current_user.role.name == "admin"
    @orders = Order.where(user_id: current_user.id) if current_user.role.name == "sales"
  end

  def show
    @order = Order.find(params[:id])
    @quote = Quote.find(@order.quote_id)

    @shipto = Shipment.where(customer_id: @quote.customer_id).where(quote_id: @quote.id).last

    @order_last_id = Order.last
    @order_first_id = Order.first
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(order_params)

    if @order.save
      redirect_to admin_orders_path, notice: "Order was successfully added"
    else
      render :new
    end
  end

  def edit
    shipped_status = OrderStatus.where('lower(name) = ?', "shipped").first
    @is_shipped = @order.order_status_id == shipped_status.id
  end

  def update
    shipped_status = OrderStatus.where('lower(name) = ?', "shipped").first
    cancelled_status = OrderStatus.where('lower(name) = ?', "cancelled").first

    if params[:order][:order_status_id].to_i == shipped_status.id
      if params[:order][:shipped_date].nil? || params[:order][:shipped_date] == ""
        params[:order][:shipped_date] = Time.zone.now
      end

      quote = Quote.find(params[:order][:quote_id])
      quote.update(status: "shipped")

      quote.quote_items.each do |quote_item|
        if quote_item.item_id.present?
          item = Item.find(quote_item.item_id)
          status = Status.where('lower(name) = ?', "out").first
          item.update(status_id: status.id)
        end
      end
    elsif params[:order][:order_status_id].to_i == cancelled_status.id
      quote = Quote.find(params[:order][:quote_id])
      quote.update(status: "quote")
    else
      ""
    end

    if @order.update(order_params)
      # Sends quote email
      if @order.order_status_id == shipped_status.id
        @quoted_order = Order.where(quote_id: @order.quote_id).last
        @salesperson = @order.user_id.present? ? @order.user.email : @quoted_order.user.email
        OrderMailer.send_order(@salesperson, @order).deliver
      end

      if @order.order_items.any?
        @status = Status.where('lower(name) = ?', "assigned").first
        @order.order_items.each do |order_item|
          item = Item.find(order_item.item_id)
          item.update(status_id: @status.id, order_id: @order.id)
        end
      else
        items = Item.where(order_id: @order.id)
        items.each do |item|
          item_o = Item.find(item.id)
          item_o.update(status_id: "in", order_id: nil)
        end
      end

      if OrderItem.where(order_id: @order.id).exists?
        order_item_ids = OrderItem.where(order_id: @order.id).pluck(:item_id)
        item_ids = Item.where(order_id: @order.id).pluck(:id)
        item_del_ids = (order_item_ids-item_ids) | (item_ids-order_item_ids)

        Item.where(id: item_del_ids).update(order_id: nil)

      end
      redirect_to admin_orders_path, notice: "Order was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @quote = Quote.find(@order.quote_id)

    if @order.destroy
      @quote.update(status: "quote")
      message = "Order destroyed successfully and Quote changed to quote status"
    else
      message = "Order can't be deleted"
    end

    respond_to do |format|
      format.html { redirect_to admin_orders_path, :notice => message }
      format.json { head :ok }
    end
  end

  def get_quote
    if params[:quote_id].present?
      @quote = Quote.find(params[:quote_id])
    end
    respond_to do |format|
      format.html {}
      format.json {render json: @quote}
    end
  end

  def update_maker_model
    if params[:maker_id].present?
      @maker_models = MakerModel.select("id, name").where(maker_id: params[:maker_id]).order("name ASC")
    else
      false
    end

    respond_to do |format|
      format.js
    end
  end

  def update_items
    if params[:maker_model_id].present?
      @items = Item.where(maker_id: params[:maker_id]).where(maker_model_id: params[:maker_model_id])
    else
      false
    end
    respond_to do |format|
      format.js
    end
  end

  def get_prev_item
    @result = Order.where("id < ?", params[:order_id]).last
    respond_to do |format|
      format.json { render json: @result }
    end
  end

  def get_next_item
    @result = Order.where("id > ?", params[:order_id]).first
    respond_to do |format|
      format.json { render json: @result }
    end
  end

  def autocomplete
    @result = Item.where("serial like ?", "%#{params[:serial].downcase}%").first
    respond_to do |format|
      format.json { render json: @result }
    end
  end


  private

  def set_id
    @order = Order.find(params[:id])
  end

  def load_data
    @quote_order_ids = Order.all.pluck(:quote_id)
    if current_user.role.name == "admin"
      @available_quotes = Quote.where.not(id: @quote_order_ids).order(:id)
      Quote.where('id NOT IN (?)', @quote_order_ids)
      @users = User.all.order(:email)
    else
      @current_users = User.where(id: current_user.id)
      @available_quotes = Quote.where(user_id: current_user.id).where.not(id: @quote_order_ids).order(:id)
    end

    @statuses = [['Quote','quote'], ['Approved','approved'], ['Shipped','shipped'], ['Cancelled', 'cancelled']]
    @delivery_methods = DeliveryMethod.all.order('name ASC')
    @delivery_types = DeliveryType.all.order('name ASC')
    @items = Item.all.order('id DESC')
    @makes = Maker.all.order(:name)
    @order_statuses = OrderStatus.all.order(:id)
  end

  def order_params
    params.require(:order).permit(:quote_id, :user_id, :delivery_method_id, :delivery_type_id, :shipped_date, :order_status_id, order_items_attributes: [:id, :item_id, :serial, :_destroy])
  end

end

app/views/admin/orders/_form.html.haml
- if @order.errors
  - @order.errors.full_messages.each do |msg|
    .alert.alert-danger#error-msg
      = msg

= form_for([:admin, @order]) do |f|
  .form-group.row
    %label.col-sm-3.col-form-label Quote
    .col-sm-7
      - if @order.new_record?
        = f.select(:quote_id, @available_quotes.collect {|a| [a.id, a.id]},  {include_blank: true}, {class: 'select2 form-control'})
      - else
        = f.text_field :quote_id, class: "form-control disabled"

  .form-group.row
    %label.col-sm-3.col-form-label Salesperson
    .col-sm-7
      - if current_user.role.name == "admin"
        = f.select(:user_id, @users.collect {|us| [us.email, us.id]},  {include_blank: true, selected: current_user.id}, {class: 'form-control select2'})
      - elsif current_user.role.name == "sales"
        = f.select(:user_id, @current_users.collect {|a| [a.email, a.id]},  {include_blank: true, selected: current_user.id}, {class: 'select2 form-control'})

  .form-group.row
    %label.col-sm-3.col-form-label Delivery Method
    .col-sm-7
      = f.select(:delivery_method_id, @delivery_methods.collect {|dm| [dm.name, dm.id]},  {include_blank: true, selected: @order.delivery_method_id.present? ? @order.delivery_method_id : nil}, {class: 'form-control select2'})

  .form-group.row
    %label.col-sm-3.col-form-label Delivery Type
    .col-sm-7
      = f.select(:delivery_type_id, @delivery_types.collect {|dt| [dt.name, dt.id]},  {include_blank: true, selected: @order.delivery_type_id.present? ? @order.delivery_type_id : nil}, {class: 'form-control select2'})

  .form-group.row
    %label.col-sm-3.col-form-label Status
    .col-sm-7
      = f.select(:order_status_id, @order_statuses.collect {|os| [os.name, os.id]}, {include_blank: true}, :class=>"form-control select2", disabled: @is_shipped)

  .form-group.row
    %label.col-sm-3.col-form-label Shipped Date
    .col-sm-7
      = f.text_field :shipped_date, class: "datepicker form-control"

  - unless @order.new_record?
    .clearfix-big
    %div.purchase-order-item
      %label ASSIGNED ITEMS

    .form-group.row
      .col-md-4
        %label Search Serial
        = text_field_tag "autocomplete", nil, class: "form-control search-input"
      .col
        %label Result:
        = text_field_tag "result_serial", nil, class: "form-control result_serial"
        = text_field_tag "result_id", nil, class: "form-control result_id hidden"
    .form-group.row
      .col
        .float-right
          %a.btn.btn-secondary.btn-sm.add-item{href: "javascript:void(0)"} Add Item

    %hr
    #order_items
      = f.fields_for :order_items do |order_item|
        = render 'order_item_fields', f: order_item

      .col-md-5
        .clearfix-sm
        = link_to_add_association "<i class='fa fa-plus'></i> Add Item".html_safe, f, :order_items, :class => "btn btn-info btn-sm btn add-order-item hidden"
        .clearfix-sm


  .clearfix-big
  .clearfix-big
  .form-group.row
    .col-sm-10
      .float-right
        %a.btn.btn-white.btn-sm{href: "/admin/orders"} Cancel
        %button.btn.btn-primary.btn-sm{:type => "submit"} Save

  .clearfix-big
  - if !@order.new_record?
    - if @order.item_ids.any?
      %label Assigned Items
      %ul.list-group
        - arry_item_ids = @order.item_ids.map(&:to_i).drop(1)
        - arry_item_ids.each do |item|
          %li.list-group-item= Item.find(item.to_i).serial || Item.find(item.to_i).id



:javascript
  $( document ).ready(function() {
    $("#order_item_ids").select2();

    $('#item_maker_id').change(function() {
      var id = $(this).val();
      return $.ajax({
        type: "GET",
        url: "/admin/orders/update_maker_model",
        data: {
          maker_id: id
        }
      });
    });

    $("#item_maker_model_id").change(function() {
      var maker_model_id = $(this).val();
      var maker_id = $('#item_maker_id').val();
      return $.ajax({
        type: "GET",
        url: "/admin/orders/update_items",
        data: {
          maker_id: maker_id,
          maker_model_id: maker_model_id
        }
      });
    });

    $('.datepicker').datepicker({
      todayHighlight: true,
      orientation: 'auto top',
      format: 'yyyy-mm-dd'
    });

    $('#order_quote_id').change(function() {
      var id = $(this).val();

      $.ajax({
        type: "GET",
        url: "/admin/orders/get_quote",
        dataType: "json",
        data: {
          quote_id: id
        },
        success: function(data) {
          console.log(data);
          $("#quote-summary").removeClass("hidden");
          $("#date-required-order").html(data.date_required);
          $("#status-order").html(data.status);
          $("#total-order").html(data.total);
          $("#total-subtotal").html(data.subtotal);
        }
      });

    });

    $(".search-input").bind('keyup', function (e) {
      if (e.which >= 97 && e.which <= 122) {
          var newKey = e.which - 32;
          e.keyCode = newKey;
          e.charCode = newKey;
      }
      $(this).val($(this).val().toUpperCase());
      var serial = $(this).val();

      $.ajax({
        type: "GET",
        url: "/admin/orders/autocomplete",
        dataType: "json",
        data: {
          serial: serial
        },
        success: function(item) {
          if((item != undefined) || (item != null)) {
            $(".result_serial").val(item.serial.toUpperCase());
            $(".result_id").val(item.id);
          }
        }
      });

    });

    $(".add-item").on("click", function(e) {
      $(".add-order-item").click();
      var id = $("#order_items").next('input').attr('id');
      var result_serial = $(".result_serial").val();
      var result_id = $(".result_id").val();
      $('#order_items .nested-fields').last().find(".serial-item").val(result_serial);
      $('#order_items .nested-fields').last().find(".serial-id").val(result_id);

      $(".result_serial").val("");
      $(".result_id").val("");
      $(".search-input").val("");
    });


  });

app/views/admin/orders/_order_item_fields.html.haml
.nested-fields#quote-fields
  = f.hidden_field :_destroy
  .form-group.row
    .col
      %label Item
      = f.text_field :serial, class: "form-control serial-item"
    .col
      %label Item ID
      = f.text_field :item_id, class: "form-control serial-id disabled"
    .col
      %br
      = link_to_remove_association "<i class='fas fa-times'></i>".html_safe, f, class: "btn btn-xs btn-danger remove_fields"

:javascript
  $( document ).ready(function() {
  });

app/views/admin/orders/edit.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Update Order
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/orders"} List View
      %li.breadcrumb-item.active
        %strong Edit
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-7
      .ibox
        .ibox-title
          %h5 Order Form
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up

        .ibox-content
          = render "form"

    .col-lg-5
      - if @order.quote_id.present?
        .ibox#quote-summary
          .ibox-title
            %h5 Quote Summary
          .ibox-content
            %table.table
              %tr
                %th Date Required
                %td= @order.quote.date_required.present? ? format_full_date(@order.quote.date_required) : "NA"
              %tr
                %th Quote Status
                %td= @order.quote.status.present? ? @order.quote.status : "NA"
              %tr
                %th Salesperson
                %td= @order.quote.user_id.present? ? @order.quote.user.email : "NA"
              %tr
                %th No. of Item/s
                %td= @order.quote.quote_items.count
              %tr
                %th Total
                %td= @order.quote.total.present? ? price_display(@order.quote.total) : "$0"
              %tr
                %th Sub Total
                %th= @order.quote.subtotal.present? ? price_display(@order.quote.subtotal) : "$0"

app/views/admin/orders/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    %h2 Orders
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/dashboard"} Dashboard
      %li.breadcrumb-item.active
        %strong List View
  .col-lg-4
    .clearfix-big
    .float-right
      %a.btn.btn-primary.mr-3{href: '/admin/orders/new'}
        %i.fa.fa-plus
        Add Order

.wrapper.wrapper-content
  - if flash.present?
    .row
      .col-lg-12
        - flash.each do |name, msg|
          = content_tag :div, msg, class: "alert alert-info"
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Orders Table
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up


        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-hover#order_dt
              %thead
                %tr
                  %th{width: "8%"} ID
                  %th Quote Id
                  %th Delivery Method
                  %th Delivery Type
                  %th Status
                  %th Approved Date
                  %th Shipped Date
              %tbody
                - @orders.each do |order|
                  %tr
                    %td
                      %a{href: "/admin/orders/#{order.id}"}
                        = "O-#{order.id}"
                    %td
                      %a{href: "/admin/quotes/#{order.quote_id}"}
                        = "Q-#{order.quote_id}"
                    %td= order.delivery_method_id.present? ? order.delivery_method.name : "NA"
                    %td= order.delivery_type_id.present? ? order.delivery_type.name : "NA"
                    %td= order.status.present? ? order.status : "NA"
                    %td= format_full_date(order.created_at)
                    %td= order.shipped_date.present? ? format_full_date(order.shipped_date) : "NA"


:javascript
  $( document ).ready(function() {
    $('#order_dt').DataTable();
  });

app/views/admin/orders/new.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Create Order
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/orders"} List View
      %li.breadcrumb-item.active
        %strong New
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-7
      .ibox
        .ibox-title
          %h5 Order Form
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up

        .ibox-content
          = render "form"

    .col-lg-5
      .ibox#quote-summary
        .ibox-title
          %h5 Quote Summary
        .ibox-content
          %table.table
            %tr
              %th Date Required
              %td
                #date-required-order
            %tr
              %th Quote Status
              %td
                #status-order
            %tr
              %th Total
              %td
                #total-order
            %tr
              %th Sub Total
              %th
                #total-subtotal

app/views/admin/orders/show.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    %h2 Order's Details
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/orders"} List View
      %li.breadcrumb-item.active
        %strong Show
  .col-lg-4
    .clearfix-big
    .float-right
      %input.hidden#lastId{:value => @order_first_id.id}
      %input.hidden#nextId{:value => @order_last_id.id}

      %a.btn.btn-default.mr-3.prevItem{href: 'javascript:void(0)', id: @order.id}
        %i.fa.fa-arrow-left
        PREV
      %a.btn.btn-default.mr-3.nextItem{href: 'javascript:void(0)', id: @order.id}
        NEXT
        %i.fa.fa-arrow-right


.wrapper.wrapper-content
  .row
    .col-lg-6
      .ibox
        .ibox-title
          %h5
            Order
            %small.m-l-sm Summary
        .ibox-content
          .row
            .col-lg-12
              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Order:
                .col-sm-9.text-sm-left
                  %dd.mb-1= @order.id
              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Quote ID:
                .col-sm-9.text-sm-left
                  %dd.mb-1
                    = @order.quote_id
                    %span
                      %a{href: "/admin/quotes/#{@order.quote_id}"} &nbsp; View Quote

              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Delivery Method:
                .col-sm-9.text-sm-left
                  %dd.mb-1= @order.delivery_method_id.present? ? @order.delivery_method.name : "NA"
              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Delivery Type:
                .col-sm-9.text-sm-left
                  %dd.mb-1= @order.delivery_type_id.present? ? @order.delivery_type.name : "NA"

              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Status:
                .col-sm-9.text-sm-left
                  %dd.mb-1= @order.order_status_id.present? ? @order.order_status.name : "NA"
              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Salesperson:
                .col-sm-9.text-sm-left
                  %dd.mb-1= @order.user.email

              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Approved Date:
                .col-sm-9.text-sm-left
                  %dd.mb-1
                    %span.label.label-primary= format_full_date(@order.created_at)

              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Shipped Date:
                .col-sm-9.text-sm-left
                  %dd.mb-1
                    %span.label.label-primary= @order.shipped_date.present? ? format_full_date(@order.shipped_date) : "NA"
              %hr
              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Requested Date:
                .col-sm-9.text-sm-left
                  %dd.mb-1= @quote.date_required.present? ? format_full_date(@quote.date_required) : "NA"
              %dl.row.mb-0
                .col-sm-3.text-sm-right
                  %dt Sub Total:
                .col-sm-9.text-sm-left= @quote.subtotal.present? ? number_to_currency(@quote.subtotal, :unit => "$ ") : "-"

              %hr
              %label Assigned Items
              %br
              - if @order.order_items.any?
                %label Serials
                %p= @order.order_items.pluck(:serial).map(&:inspect).join(', ')

          .clearfix-big
          .row
            .col-lg-4
              = link_to "Delete", admin_order_path(@order.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger btn-block'

            .col-lg-4
              %a.btn.btn-primary.btn-block{href: "/admin/orders/#{@order.id}/edit"}
                %i.fa.fa-edit
                Edit

    .col-lg-6
      .ibox
        .ibox-title
          %h5
            Order
            %small.m-l-sm Details

        .ibox-content
          .row
            .col-lg-12
              %label Customer
              .table-responsive
                %table.table.table-bordered.table-hover
                  %tr
                    %th Name
                    %td= @quote.customer_id.present? ? @quote.customer.name : "NA"
              %label Ship To
              - if @shipto.present?
                .table-responsive
                  %table.table.table-bordered.table-hover
                    %tr
                      %th Address 1
                      %td= @shipto.address1
                    %tr
                      %th Address 2
                      %td= @shipto.address2
                    %tr
                      %th City
                      %td= @shipto.city_code
                    %tr
                      %th Province
                      %td= @shipto.state_name
                    %tr
                      %th Country
                      %td= @shipto.country_name
                    %tr
                      %th Postal Code
                      %td= @shipto.postal_code

              - else
                .table-responsive
                  %table.table.table-bordered.table-hover
                    %tr
                      %th Address 1
                      %td= @quote.customer.address1
                    %tr
                      %th Address 2
                      %td= @quote.customer.address2
                    %tr
                      %th City
                      %td= @quote.customer.city_code
                    %tr
                      %th Province
                      %td= @quote.customer.state_name
                    %tr
                      %th Country
                      %td= @quote.customer.country_name
                    %tr
                      %th Postal Code
                      %td= @quote.customer.postal_code


  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            Order
            %small.m-l-sm Items
        .ibox-content
          .table-responsive
            %table.table.table-bordered.table-hover#order_dt
              %thead
                %tr
                  %th{width: "5%"} ID
                  %th{width: "10%"} Warranty
                  %th{width: "12%"} Make
                  %th{width: "12%"} Model
                  %th{width: "10%"} Part Number
                  %th Description
                  %th{width: "5%"} QTY
                  %th{width: "8%"} Each Price
              %tbody
                - @quote.quote_items.each do |quote_item|
                  %tr
                    %td= quote_item.id
                    %td= quote_item.warranty_id.present? ? ProductWarranty.where(id: quote_item.warranty_id).first.name : "NA"
                    %td= quote_item.maker_id.present? ? quote_item.maker.name : "NA"
                    %td= quote_item.maker_model_id.present? ? quote_item.maker_model.name : "NA"
                    %td= quote_item.part_number.present? ? quote_item.part_number : "NA"
                    %td= quote_item.description.present? ? quote_item.description : "NA"
                    %td= quote_item.qty.present? ? quote_item.qty : 0
                    %td= quote_item.each_price.present? ? quote_item.each_price : 0



:javascript
  $( document ).ready(function() {
    var lastId = $("#lastId").val();
    if(lastId == "#{@order.id}") {
      $('.prevItem').addClass( "disabled" );
    } else {
      $('.prevItem').removeClass( "disabled" );
    }

    var nextId = $("#nextId").val();
    if(nextId == "#{@order.id}") {
      $('.nextItem').addClass( "disabled" );
    } else {
      $('.nextItem').removeClass( "disabled" );
    }

    $('.prevItem').on('click', function (e) {
      var order_id = $(this).attr('id');

      $.ajax({
        type: "GET",
        url: "/admin/orders/get_prev_item",
        dataType: "json",
        data: {
          order_id: order_id
        },
        success: function(data) {
          window.location.href = "/admin/orders/"+data.id;
        }
      });

    });

    $('.nextItem').on('click', function (e) {
      var order_id = $(this).attr('id');

      $.ajax({
        type: "GET",
        url: "/admin/orders/get_next_item",
        dataType: "json",
        data: {
          order_id: order_id
        },
        success: function(data) {
          window.location.href = "/admin/orders/"+data.id;
        }
      });

    });
  });

app/views/admin/orders/update_items.js.erb
$('#order_item_ids').html("<%= j options_for_select(@items.map {|item| [item.serial,item.id]}) %>");

app/views/admin/orders/update_maker_model.js.erb
$('#item_maker_model_id').html("<%= j options_for_select(@maker_models.map {|mm| [mm.name,mm.id]}) %>");