config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :controllers => { sessions: 'sessions'}

  root to: 'home#index'

  namespace :admin do
    resources :dashboard, only: :index

    resources :orders do
      collection do
        get :get_quote
        get :update_maker_model
        get :update_items
        get :get_prev_item
        get :get_next_item
        get :autocomplete
      end
    end

    resources :skus

    resources :audits do
      collection do
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
      end
    end

    resources :purchase_orders do
      collection do
        get :get_states
        get :get_cities
        get :get_vendor_details
        get :get_warehouse_details
        post :clone_with_item
        post :clone
        post :add_to_inventory
        get :get_prev_item
        get :get_next_item
        get :get_tax_details
      end
    end

    resources :reports do
      collection do
        get :convert
        get :pdf
      end
    end

    # === Settings ===
    resources :devices
    resources :categories
    resources :makers
    resources :statuses
    resources :order_statuses
    resources :condition_types
    resources :grades
    resources :payment_methods
    resources :delivery_methods
    resources :delivery_types
    resources :customer_types
    resources :terms
    resources :departments
    resources :product_warranties
    resources :product_types
    resources :taxes do
      collection do
        get :get_states
      end
    end
    # === Settings ===

    #  === People ===
    resources :users
    resources :vendors do
      collection do
        get :get_states
        get :get_cities
      end
    end
    # resources :companies do
    #   collection do
    #     get :get_states
    #     get :get_cities
    #   end
    # end
    resources :customers do
      collection do
        get :get_states
        get :get_cities
        get :get_taxes
      end
    end
    #  === People ===

    resources :warehouses do
      collection do
        get :get_states
        get :get_cities
      end
    end

    resources :items do
      collection do
        get :update_maker_model
        get :update_sub_category
        get :set_device
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
        get :editable
        get :barcodes
        get :edit_all
        get :get_subcategories
        get :get_makermodels
      end
    end

    resources :quotes do
      collection do
        get :get_customer_details
        get :get_item_details
        get :update_models
        get :update_items
        get :get_states
        get :get_cities
        get :get_states_customer
        get :get_cities_customer
        get :get_tax_details
        get :send_email
        get :approve_quote
        get :get_prev_item
        get :get_next_item
      end
    end

    resources :import_data
    resources :tutorial, only: :index

  end

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < AdminController

  def index
    if params[:report].present?
      if params[:report][:name] == "Sales"
        start_date = Time.zone.parse(params[:report][:start_date])
        end_date = Time.zone.parse(params[:report][:end_date])
        @result = Quote.where( 'created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day)
        @sales = Quote.select("id, user_id, sum(subtotal) as total_sale").where( 'created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day).group("id, user_id")

        @sales_by_salesperson = Quote.joins(:user).where( 'quotes.created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day).group("users.email").sum(:subtotal)
        quote_items = QuoteItem.where(quote_id: @result.pluck(:id))

        item_categories = []
        quote_items.each do |quote_item|
          item_categories << { Category.find(quote_item.item.category_id).name => quote_item.qty} if quote_item.item_id.present?
        end

        @item_sold_by_category = item_categories.group_by { |h| h.keys.first }.map do |k, v|
          Array[k, v.reduce(0) { |acc, n| acc + n.values.first.to_i }]
        end


        @average_by_salesperson = []
        @result.each do |res|
          avg = @result.sum(:subtotal)/@result.count
          if res.user_id.present?
            @average_by_salesperson << [res.user.email, avg.to_i]
          end
        end
      end


    else
      start_date = Time.zone.now
      end_date = Time.zone.now
      @result = Quote.where( 'created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day)
      @sales = Quote.select("id, user_id, sum(subtotal) as total_sale").where( 'created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day).group("id, user_id")

      @sales_by_salesperson = Quote.joins(:user).where( 'quotes.created_at BETWEEN ? AND ?', start_date.beginning_of_day, end_date.end_of_day).group("users.email").sum(:subtotal)
      quote_items = QuoteItem.where(quote_id: @result.pluck(:id))


      item_categories = []
      quote_items.each do |quote_item|
        item_categories << { Category.find(quote_item.item.category_id).name => quote_item.qty} if quote_item.item_id.present?
      end


      @item_sold_by_category = item_categories.group_by { |h| h.keys.first }.map do |k, v|
        Array[k, v.reduce(0) { |acc, n| acc + n.values.first.to_i }]
      end


      @average_by_salesperson = []
      @result.each do |res|
        avg = @result.sum(:subtotal)/@result.count
        if res.user_id.present?
          @average_by_salesperson << [res.user.email, avg.to_i]
        end
      end

    end

  end

  def convert
    if params[:data] == "audit"
      @file_name = "Audits-Report"
      @data = Audit.all.order("id ASC")
    elsif params[:data] == "item"
      @file_name = "Inventory-Report"
      @data = Item.all.order("id ASC")
    elsif params[:data] == "vendor"
      @file_name = "Vendors-Report"
      @data = Vendor.all.order("id ASC")
    elsif params[:data] == "user"
      @file_name = "Users-Report"
      @data = User.all.order("id ASC")
    else
    end



    respond_to do |format|
      format.html
      format.csv { send_data @data.to_csv, filename: "#{@file_name}-#{Date.today}.csv" }
    end
  end

end

app/views/admin/reports/_main.js.erb
var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var config = {
	type: 'line',
	data: {
		labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		datasets: [{
			label: 'My First dataset',
			borderColor: "#C6C22F",
			backgroundColor: "#C6C22F",
			data: [
				44,
				55,
				20,
				21,
				89,
				52,
				33
			],
		}, {
			label: 'My Second dataset',
			borderColor: "#4DAA33",
			backgroundColor: "#4DAA33",
			data: [
				24,
				55,
				60,
				11,
				89,
				82,
				73
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#C559A5",
			backgroundColor: "#C559A5",
			data: [
				41,
				55,
				94,
				61,
				81,
				52,
				30
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#45CCB7",
			backgroundColor: "#45CCB7",
			data: [
				23,77,58,43,45,75,32
			],
		}]
	},
	options: {
		responsive: true,
		title: {
			display: true,
			text: 'Chart.js Line Chart - Stacked Area'
		},
		tooltips: {
			mode: 'index',
		},
		hover: {
			mode: 'index'
		},
		scales: {
			xAxes: [{
				scaleLabel: {
					display: true,
					labelString: 'Month'
				}
			}],
			yAxes: [{
				stacked: true,
				scaleLabel: {
					display: true,
					labelString: 'Value'
				}
			}]
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('sample').getContext('2d');
	window.myLine = new Chart(ctx, config);
};

app/views/admin/reports/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 All Reports
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/dashboard"} Dashboard
      %li.breadcrumb-item.active
        %strong Reports
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Report
        .ibox-content#report-form
          = form_tag admin_reports_path, method: :get do
            .row
              .col-md-4
                %label Report Date:
                %span.ml-2.date-result
                  - if params[:report].present?
                    - if params[:report][:start_date] == params[:report][:end_date]
                      = params[:report][:start_date]
                    - else
                      = "#{params[:report][:start_date]} - #{params[:report][:end_date]}"
                  - else
                    = format_full_date(Date.today)

              .col-md-2
                = select_tag "report[name]", options_for_select([["Sales", "Sales"]]), class: "form-control select2"
              .col-md-3
                #reportrange{:style => "background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%"}
                  %i.fa.fa-calendar
                  %span
                  %i.fa.fa-caret-down
                = hidden_field_tag "report[start_date]"
                = hidden_field_tag "report[end_date]"
              .col-md-3
                %a.btn.btn-default-outline{href: "/admin/dashboard"} Reset
                = submit_tag 'Generate Report', class: 'btn btn-secondary'

          .clearfix
          %hr
          .row
            .col-md-12
              - if @result.present?
                .row
                  .col-md-5
                    %label Sales Totals
                    %dl.small.m-t-md
                      %dt Total Sales
                      %dd= number_to_currency(@result.sum(:subtotal), :unit => "$ ", :precision => 2)
                      %dt Total Freight
                      %dd= number_to_currency(@result.sum(:freight), :unit => "$ ", :precision => 2)
                      %dt Total Quotes
                      %dd= @result.count
                      %dt Average Per Quote
                      %dd= number_to_currency((@result.sum(:subtotal) / @result.count), :unit => "$ ", :precision => 2)
                  .col-md-4
                    %label Sales By Salesperson
                    .clearfix
                    #sales-by-salesperson
                      %table.table.table-condensed.table-sm.table-bordered
                        %thead
                          %tr
                            %th{:scope => "col"} Salesperson
                            %th{:scope => "col"} Total
                        %tbody
                          - @sales.each do |sale|
                            %tr
                              %td= sale.user.email
                              %td= number_to_currency(sale.total_sale, :unit => "$ ")




              - else
                .alert.alert-secondary
                  No Report

          .clearfix
          %hr
          .clearfix
          .row
            .col-md-12
              #table-300
                - if @result.present?
                  %table.table.table-bordered.table-hover
                    %thead
                      %tr
                        %th Quote ID
                        %th Date Created
                        %th Salesperson
                        %th Customer
                    %tbody
                      - @result.each do |result|
                        %tr
                          %td= result.id
                          %td= format_full_date(result.created_at)
                          %td= result.user.email
                          %td= result.customer.name


          .clearfix
          %hr
          .clearfix
          .row
            .col-md-6.text-center
              %label Sales By Salesperson
              .clearfix
              = pie_chart @sales_by_salesperson
            .col-md-6.text-center
              %label Item Sold By Category
              .clearfix
              = pie_chart @item_sold_by_category, colors: ["#1ab394", "#0d98b7", "#aa10dc", "#f1197d", "#f17219", "#FFEB3B"]


          %br
          %hr
          .row
            .col-md-12.text-center
              %label Average by Salesperson
              .clearfix
              = column_chart @average_by_salesperson


  .clearfix-big

  .row
    .col-lg-12
      .page-header
        %h1 Other Reports

  .clearfix
  .row
    .col-lg-6
      .ibox
        .ibox-title
          %h5 Inventory Items
          .ibox-tools
            = link_to "Export Data", convert_admin_reports_path(format: "csv", :data => "item"), class: "btn btn-default btn-xs"

            %a.collapse-link#item-report
              %i.fa.fa-chevron-up
        .ibox-content.item-report
          = column_chart Item.group_by_day_of_week(:created_at, format: "%a").count

    .col-lg-6
      .ibox
        .ibox-title
          %h5 Audited Items
          .ibox-tools
            = link_to "Export Data", convert_admin_reports_path(format: "csv", :data => "audit"), class: "btn btn-default btn-xs"
            %a.collapse-link#audit-report
              %i.fa.fa-chevron-up
        .ibox-content.audit-report
          = column_chart Audit.group_by_day_of_week(:audited_date, format: "%a").count



  .row
    .col-lg-6
      .ibox
        .ibox-title
          %h5 Users
          .ibox-tools
            = link_to "Export Data", convert_admin_reports_path(format: "csv", :data => "user"), class: "btn btn-default btn-xs"
            %a.collapse-link#user-report
              %i.fa.fa-chevron-up
        .ibox-content.user-report
          = line_chart User.group_by_day(:created_at).count

    .col-lg-6
      .ibox
        .ibox-title
          %h5 Vendors
          .ibox-tools
            = link_to "Export Data", convert_admin_reports_path(format: "csv", :data => "vendor"), class: "btn btn-default btn-xs"
            %a.collapse-link#vendor-report
              %i.fa.fa-chevron-up
        .ibox-content.vendor-report
          = line_chart Vendor.group_by_month(:created_at).count


:javascript
  $( document ).ready(function() {
    $('.collapse-link').on('click', function (e) {
      var id = $(this).attr('id');
      $("."+id).slideToggle(200);
    });

    var today = moment().format('LL');
    $("#date-result").html(today);

    var start = moment().subtract(29, 'days');
    var end = moment();

    function cb(start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));

        $("#report_start_date").val(start.format('MMMM D, YYYY'));
        $("#report_end_date").val(end.format('MMMM D, YYYY'));
    }

    $('#reportrange').daterangepicker({
        startDate: start,
        endDate: end,
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);

    cb(start, end);

  });