config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :controllers => { sessions: 'sessions'}

  root to: 'home#index'

  namespace :admin do
    resources :dashboard, only: :index

    resources :orders do
      collection do
        get :get_quote
        get :update_maker_model
        get :update_items
        get :get_prev_item
        get :get_next_item
        get :autocomplete
      end
    end

    resources :skus

    resources :audits do
      collection do
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
      end
    end

    resources :purchase_orders do
      collection do
        get :get_states
        get :get_cities
        get :get_vendor_details
        get :get_warehouse_details
        post :clone_with_item
        post :clone
        post :add_to_inventory
        get :get_prev_item
        get :get_next_item
        get :get_tax_details
      end
    end

    resources :reports do
      collection do
        get :convert
        get :pdf
      end
    end

    # === Settings ===
    resources :devices
    resources :categories
    resources :makers
    resources :statuses
    resources :order_statuses
    resources :condition_types
    resources :grades
    resources :payment_methods
    resources :delivery_methods
    resources :delivery_types
    resources :customer_types
    resources :terms
    resources :departments
    resources :product_warranties
    resources :product_types
    resources :taxes do
      collection do
        get :get_states
      end
    end
    # === Settings ===

    #  === People ===
    resources :users
    resources :vendors do
      collection do
        get :get_states
        get :get_cities
      end
    end
    # resources :companies do
    #   collection do
    #     get :get_states
    #     get :get_cities
    #   end
    # end
    resources :customers do
      collection do
        get :get_states
        get :get_cities
        get :get_taxes
      end
    end
    #  === People ===

    resources :warehouses do
      collection do
        get :get_states
        get :get_cities
      end
    end

    resources :items do
      collection do
        get :update_maker_model
        get :update_sub_category
        get :set_device
        get :lists
        get :get_prev_item
        get :get_next_item
        post :clone
        get :editable
        get :barcodes
        get :edit_all
        get :get_subcategories
        get :get_makermodels
      end
    end

    resources :quotes do
      collection do
        get :get_customer_details
        get :get_item_details
        get :update_models
        get :update_items
        get :get_states
        get :get_cities
        get :get_states_customer
        get :get_cities_customer
        get :get_tax_details
        get :send_email
        get :approve_quote
        get :get_prev_item
        get :get_next_item
      end
    end

    resources :import_data
    resources :tutorial, only: :index

  end

end

app/models/quote.rb
class Quote < ApplicationRecord

  belongs_to :customer
  has_many :quote_items
  accepts_nested_attributes_for :quote_items, reject_if: :all_blank, allow_destroy: true

  has_many :items, :through => :quote_items
  has_many :shipments, :dependent => :destroy
  has_many :send_logs, :dependent => :destroy
  belongs_to :tax, optional: true
  belongs_to :user, optional: true
  belongs_to :term, optional: true
  has_many :orders, :dependent => :destroy

end

app/controllers/admin/quotes_controller.rb
class Admin::QuotesController < AdminController

  before_action :load_data, :only=> [:index, :new, :edit, :create, :update, :search]
  before_action :set_id, :only=> [:show, :edit, :update, :destroy]
  before_action :customer_values, :only => [:edit, :new]

  def index
    params.permit!
    if params[:quote].present?
      search = params[:quote].select {|k,v| v != ""}
      quote_params = search.to_h
      @quotes = Quote.where(quote_params).order("id DESC") if current_user.role.name == "admin"
      @quotes = Quote.where(user_id: current_user.id).where(quote_params).order("id DESC") if current_user.role.name == "sales"
    else
      @quotes = Quote.all.order("id DESC") if current_user.role.name == "admin"
      @quotes = Quote.where(user_id: current_user.id).order("id DESC") if current_user.role.name == "sales"
    end
    @statuses = [['Quote','quote'], ['Approved','approved'], ['Shipped','shipped'], ['Cancelled', 'cancelled']]
  end

  def new
    @quote = Quote.new
    @statuses = [['Quote','quote'], ['Approved','approved'], ['Shipped','shipped'], ['Cancelled', 'cancelled']]
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.customer_id == 0 || @quote.customer_id.nil?
      if params[:quote][:customer_id].present?
        customer_params = {
          name: params[:quote][:customer_id],
          address1: params[:customer][:address1],
          address2: params[:customer][:address2],
          country_code: params[:customer][:country_code],
          province_code: params[:customer][:province_code],
          city_code: params[:customer][:city_code],
          postal_code: params[:customer][:postal_code],
          phone_number: params[:customer][:phone_number],
          fax_number: params[:customer][:fax_number],
          contact_name: params[:customer][:contact_name],
          email: params[:customer][:email]
        }
        @customer = Customer.create!(customer_params)
        @quote.customer_id = @customer.id
      end
    end

    if @quote.save
      @quote.quote_items.each do |quote_item|
        if quote_item.item_id.present?
          item = Item.find(quote_item.item_id)
          item.update(quote_id: quote_item.quote_id)
        end
        if quote_item.part_number.present?
          if Item.where('lower(part_number) = ?', quote_item.part_number.downcase.strip).exists?
            item = Item.where('lower(part_number) = ?', quote_item.part_number.downcase.strip).last
            item.update(quote_id: quote_item.quote_id)
            quote_item.update(item_id: item.id)
          end
        end
      end

      if params[:shipment][:address1].present?
        params[:shipment][:country_code] = @quote.customer.country_code if params[:shipment][:country_code] == ""
        params[:shipment][:province_code] = @quote.customer.province_code if params[:shipment][:province_code] == ""
        params[:shipment][:city_code] = @quote.customer.city_code if params[:shipment][:city_code] == ""

        shipment_params = {
          customer_id: @quote.customer_id,
          quote_id: @quote.id,
          address1: params[:shipment][:address1],
          address2: params[:shipment][:address2],
          country_code: params[:shipment][:country_code],
          province_code: params[:shipment][:province_code],
          city_code: params[:shipment][:city_code],
          postal_code: params[:shipment][:postal_code],
          contact_name: params[:shipment][:contact_name],
          email: params[:shipment][:email]
        }
        @shipment = Shipment.create!(shipment_params)
      end

      if @quote.status == "cancelled"
        if Order.where(quote_id: @quote.id).exists?
          order = Order.where(quote_id: @quote.id).last
          order.destroy
        end
      elsif @quote.status == "approved"
        # check order first
        order = Order.where(quote_id: @quote.id).exists?
        unless order
          os = OrderStatus.where('lower(name) = ?', "processing").first
          Order.create(quote_id: @quote.id, user_id: @quote.user_id, order_status_id: os.id)
        end
      elsif @quote.status == "shipped"
        order = Order.where(quote_id: @quote.id).exists?
        os = OrderStatus.where('lower(name) = ?', "shipped").first
        if order
          o = Order.where(quote_id: @quote.id).last
          o.update(order_status_id: os.id, shipped_date: Time.zone.now)
        else
          Order.create(quote_id: @quote.id, user_id: @quote.user_id, order_status_id: os.id, shipped_date: Time.zone.now)
        end
      end

      redirect_to admin_quote_path(@quote), notice: "Successfully Added"
    else
      render :new
    end
  end

  def edit
    @statuses = [['Quote','quote'], ['Approved','approved'], ['Shipped','shipped'], ['Cancelled', 'cancelled']]
  end

  def update
    if @quote.customer_id == 0 || @quote.customer_id.nil?
      customer_params = {
        name: params[:quote][:customer_id],
        address1: params[:customer][:address1],
        address2: params[:customer][:address2],
        country_code: params[:customer][:country_code],
        province_code: params[:customer][:province_code],
        city_code: params[:customer][:city_code],
        postal_code: params[:customer][:postal_code],
        phone_number: params[:customer][:phone_number],
        fax_number: params[:customer][:fax_number],
        contact_name: params[:customer][:contact_name],
        email: params[:customer][:email]
      }
      @customer = Customer.create!(customer_params)
      @quote.customer_id = @customer.id
    end

    if params[:quote][:status] == "cancelled"
      order = Order.where(quote_id: @quote.id).last
      order.destroy
    elsif params[:quote][:status] == "approved"
      # check order first
      order = Order.where(quote_id: @quote.id).exists?
      unless order
        os = OrderStatus.where('lower(name) = ?', "processing").first
        Order.create(quote_id: @quote.id, user_id: @quote.user_id, order_status_id: os.id)
      end
    elsif params[:quote][:status] == "shipped"
      order = Order.where(quote_id: @quote.id).exists?
      os = OrderStatus.where('lower(name) = ?', "shipped").first
      if order
        o = Order.where(quote_id: @quote.id).last
        o.update(order_status_id: os.id, shipped_date: Time.zone.now)
      else
        Order.create(quote_id: @quote.id, user_id: @quote.user_id, order_status_id: os.id, shipped_date: Time.zone.now)
      end
    end

    if @quote.update(quote_params)

      @quote.quote_items.each do |quote_item|
        if quote_item.item_id.present?
          item = Item.find(quote_item.item_id)
          item.update_attributes(quote_id: quote_item.quote_id)
        end

        if quote_item.part_number.present?
          if Item.where('lower(part_number) = ?', quote_item.part_number.downcase.strip).exists?
            item = Item.where('lower(part_number) = ?', quote_item.part_number.downcase.strip).last
            item.update(quote_id: quote_item.quote_id)

            quote_item.update(item_id: item.id)
          end
        end
      end

      if params[:shipment][:address1].present?
        shipment_params = {
          customer_id: @quote.customer_id,
          quote_id: @quote.id,
          address1: params[:shipment][:address1],
          address2: params[:shipment][:address2],
          country_code: params[:shipment][:country_code],
          province_code: params[:shipment][:province_code],
          city_code: params[:shipment][:city_code],
          postal_code: params[:shipment][:postal_code],
          contact_name: params[:shipment][:contact_name],
          email: params[:shipment][:email]
        }
        @shipment = Shipment.create!(shipment_params)
      end

      redirect_to "/admin/quotes/#{@quote.id}", notice: "Quote was successfully updated"
    else
      render :edit
    end
  end

  def show
    @shipment = Shipment.where(quote_id: @quote.id).last
    @salespersons = User.where(role_id: 2)

    @send_logs = SendLog.where(quote_id: @quote.id).order("id DESC")
    @order = Order.where(quote_id: @quote.id).last

    @quote_last_id = Quote.last
    @quote_first_id = Quote.first

  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #       render pdf: "PDF_SAMPLE",
  #              template: 'layouts/show.pdf.erb',
  #              layout: 'show.pdf',
  #              show_as_html: params[:debug].present?,
  #       outline: {
  #         outline: true,
  #         outline_depth: 50
  #       },
  #       margin: {
  #         top: 35,
  #         bottom: 35,
  #         left: 35,
  #         right: 35
  #       },
  #       print_media_type: true,
  #       disable_javascript: false
  #     end
  #   end
  end

  def get_customer_details
    customer_id = params[:customer_id].to_i
    @customer = Customer.find(customer_id)

    if @customer.tax_id.present?
      @tax = Tax.where(id: @customer.tax_id).first
      @data = {
        id: @customer.id,
        name: @customer.name,
        address1: @customer.address1,
        address2: @customer.address2,
        city_code: @customer.city_code,
        country_code: @customer.country_code,
        province_code: @customer.province_code,
        postal_code: @customer.postal_code,
        phone_number: @customer.phone_number,
        fax_number: @customer.fax_number,
        contact_name: @customer.contact_name,
        email: @customer.email,
        tax_id: @customer.tax_id,
        percentage: @tax.percentage
      }
    else
      @data = {
        id: @customer.id,
        name: @customer.name,
        address1: @customer.address1,
        address2: @customer.address2,
        city_code: @customer.city_code,
        country_code: @customer.country_code,
        province_code: @customer.province_code,
        postal_code: @customer.postal_code,
        phone_number: @customer.phone_number,
        fax_number: @customer.fax_number,
        contact_name: @customer.contact_name,
        email: @customer.email,

app/views/admin/quotes/_filter.html.haml
= form_tag admin_quotes_path, method: :get do
  .form-group.row
    .col-md-1
      %label Quote ID
      = select_tag "quote[id]", options_from_collection_for_select(@quotes, "id", "id", params[:quote].present? ? params[:quote][:quote_purchase_number] : nil), include_blank: true, class: 'form-control select2'
    .col
      %label Salesperson
      = select_tag "quote[user_id]", options_from_collection_for_select(@usersales, "id", "email", params[:quote].present? ? params[:quote][:user_id] : nil), include_blank: true, class: 'form-control select2'
    .col
      %label Customer
      = select_tag "quote[customer_id]", options_from_collection_for_select(@customers, "id", "name", params[:quote].present? ? params[:quote][:customer_id] : nil), include_blank: true, class: 'form-control select2'
    .col
      %label Quote Date
      = text_field_tag "quote[quote_date]", params[:quote].present? ? params[:quote][:quote_date] : nil, class: "datepicker form-control"
    .col
      %label Required Date
      = text_field_tag "quote[date_required]", params[:quote].present? ? params[:quote][:required_date] : nil, class: "datepicker form-control"
    .col
      %label Term
      = select_tag "quote[term_id]", options_from_collection_for_select(@terms, "id", "name", params[:quote].present? ? params[:quote][:term_id] : nil), include_blank: true, class: 'form-control select2'

    .col
      %label Status
      = select_tag "quote[status]", options_for_select(@statuses, params[:quote].present? ? params[:quote][:status] : nil), include_blank: true, class: 'form-control select2'

  .clearfix-sm
  %hr
  .form-group.row
    .col-md-12
      .float-right
        %a.btn.btn-default{href: "/admin/quotes"} Reset
        = submit_tag 'Search', class: 'btn btn-secondary'

:javascript
  $(document).ready(function() {
    $('.datepicker').datepicker({
      todayHighlight: true,
      orientation: 'auto top',
      format: 'yyyy-mm-dd'
    });

    $('.select2').select2({
      placeholder: "Select",
      allowClear: true,
      width: '100%'
    });
  });

app/views/admin/quotes/_quote_item_fields.html.haml
.nested-fields#quote-fields
  = f.hidden_field :_destroy
  .box-nested
    .form-group.row
      .col
        %label Warranty
        = f.select(:warranty_id, @warranties.collect {|w| [w.name, w.id]},  {include_blank: true}, {class: 'form-control select2'})
      .col
        %label Make
        = f.select(:maker_id, @makes.collect {|m| [m.name, m.id]},  {include_blank: true}, {class: 'maker-select form-control select2'})
      .col
        %label Model
        = f.select(:maker_model_id, @maker_models.collect {|m| [m.name, m.id]},  {include_blank: true}, {class: 'maker-model-select form-control select2'})
      .col
        %label Part #
        = f.text_field :part_number, class: 'form-control'
      .col
        %label Grade
        = f.select(:grade_id, @grades.collect {|t| [t.name, t.id]}, {include_blank: true}, {class: 'form-control select2'})
    .form-group.row
      .col-md-7
        %label Description
        = f.text_field :description, class: 'form-control'
      .col
        %label QTY
        = f.number_field :qty, class: 'form-control item-qty'
      .col
        %label Selling
        = f.text_field :each_price, class: 'form-control item-selling'

      .col
        %label Total
        = f.text_field :item_subtotal, class: 'item-subtotal form-control'


      .col
        %br
        = link_to_remove_association "<i class='fas fa-times'></i>".html_safe, f, class: "btn btn-xs btn-danger remove_fields"

:javascript
  $( document ).ready(function() {

    $('.select2').select2({
      placeholder: "Select",
      allowClear: true
    });

    $('.item-qty').bind('keyup mouseup', function () {
      var selectId = $(this).attr("id");
      var numb = selectId.match(/\d/g);
      numb = numb.join("");

      var qty = numb+"_qty";
      var rate = numb+"_each_price";
      var total = numb+"_item_subtotal";

      var qty_val = $("#quote_quote_items_attributes_"+qty).val();
      var rate_val = $("#quote_quote_items_attributes_"+rate).val();

      var compute = parseFloat(qty_val) * parseFloat(rate_val);

      $("#quote_quote_items_attributes_"+total).val(compute);

      var arr = $(".item-subtotal");
      var tot=0;
      for(var i=0;i<arr.length;i++){
        if(parseFloat(arr[i].value))
            tot += parseFloat(arr[i].value);
      }

      var tax = $("#quote_tax_percentage").val();
      if (tax == "") {
        tax = 0;
      }
      var tax_amount =  ((parseFloat(tax)/ 100) * parseFloat(tot)).toFixed(2)

      $("#quote_tax_amount").val(tax_amount);

      $("#quote_subtotal").val(parseFloat(tot).toFixed(2));

      var freight = $("#quote_freight").val();
      if (freight == "") {
        freight = 0;
      }
      var final_computation = (parseFloat(tot) + parseFloat(tax_amount) + parseFloat(freight));

      $("#quote_total").val(final_computation);

    });

    $('.item-selling').bind('keyup mouseup', function () {

      var selectId = $(this).attr("id");
      var numb = selectId.match(/\d/g);
      numb = numb.join("");

      var qty = numb+"_qty";
      var rate = numb+"_each_price";
      var total = numb+"_item_subtotal";

      var qty_val = $("#quote_quote_items_attributes_"+qty).val();
      var rate_val = $("#quote_quote_items_attributes_"+rate).val();

      var compute = parseFloat(qty_val) * parseFloat(rate_val);

      $("#quote_quote_items_attributes_"+total).val(compute);

      var arr = $(".item-subtotal");
      var tot=0;
      for(var i=0;i<arr.length;i++){
        if(parseFloat(arr[i].value))
            tot += parseFloat(arr[i].value);
      }

      var tax = $("#quote_tax_percentage").val();
      if (tax == "") {
        tax = 0;
      }
      var tax_amount =  ((parseFloat(tax)/ 100) * parseFloat(tot)).toFixed(2)

      $("#quote_tax_amount").val(tax_amount);

      $("#quote_subtotal").val(parseFloat(tot).toFixed(2));

      var freight = $("#quote_freight").val();
      if (freight == "") {
        freight = 0;
      }
      var final_computation = (parseFloat(tot) + parseFloat(tax_amount) + parseFloat(freight));

      $("#quote_total").val(final_computation);

    });


    // $(document).on('change', '.part-number', function(){
    //   var selectId = $(this).attr('id');
    //   var itemId = $('#'+selectId).val();
    //
    //   $.ajax({
    //      type: "GET",
    //      url: "/admin/quotes/get_item_details",
    //      dataType: "json",
    //      data: {
    //        item_id: itemId
    //      },
    //      success: function(item) {
    //         var numb = selectId.match(/\d/g);
    //         numb = numb.join("");
    //         var descriptionId = numb+"_description";
    //         var priceId = numb+"_each_price";
    //         var qtyId = numb+"_qty";
    //
    //         var cost = item.cost || 0;
    //         var addson = item.cost_of_addons || 0;
    //         var freight = item.cost_of_freight || 0;
    //
    //         $("#quote_quote_items_attributes_"+descriptionId).val(item.description);
    //         $("#quote_quote_items_attributes_"+priceId).val(item.cost);
    //
    //         $( "#quote_quote_items_attributes_"+qtyId).bind('keyup mouseup', function () {
    //           var qty_count = $(this).val();
    //           var amount = ((parseFloat(cost) + parseFloat(addson) + parseFloat(freight)) * parseInt(qty_count));
    //
    //           var arr = $(".item-subtotal");
    //           var tot=0;
    //           for(var i=0;i<arr.length;i++){
    //             if(parseFloat(arr[i].value))
    //                 tot += parseFloat(arr[i].value);
    //           }
    //
    //           $("#quote_total").val(tot);
    //
    //         });
    //
    //      }
    //   });
    //
    // });


    $('.maker-select').change(function() {
      var id = $(this).val();
      var selectId = $(this).attr('id');

      var numb = selectId.match(/\d/g);
      numb = numb.join("");
      var modelId = numb+"_maker_model_id";
      var select = $("#quote_quote_items_attributes_"+modelId);


      select.empty();


      $.ajax({
        type: "GET",
        url: "/admin/quotes/update_models",
        dataType: "json",
        data: {
          make_id: id
        },
        success: function(models) {


          for (var j = 0; j < models.length; j++){
            select.prepend("<option value='' selected='selected'></option>");
            select.append($("<option></option>").attr("value", models[j].id ).text(models[j].name));
          };
        }
      });
    });

  });

app/views/admin/quotes/edit.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Update Quote
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/quotes"} List View
      %li.breadcrumb-item.active
        %strong Edit
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Quote Form
          .ibox-tools
            %a.collapse-link#quote-edit
              %i.fa.fa-chevron-up

        .ibox-content.quote-edit
          = render "form"

:javascript
  $( document ).ready(function() {
    $('.collapse-link').on('click', function (e) {
      var id = $(this).attr('id');
      $("."+id).slideToggle(200);
    });
  });

app/views/admin/quotes/get_cities.js.erb
$('#shipment_city_code').html("<%= j options_for_select(@cities) %>");

app/views/admin/quotes/get_cities_customer.js.erb
$('#customer_city_code').html("<%= j options_for_select(@cities) %>");

app/views/admin/quotes/get_states.js.erb
$('#shipment_province_code').html("<%= j options_for_select(@states.map {|k,v| [v,k]}) %>");

app/views/admin/quotes/get_states_customer.js.erb
$('#customer_province_code').html("<%= j options_for_select(@states.map {|k,v| [v,k]}) %>");

app/views/admin/quotes/index.html.haml
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js", :type => "text/javascript"}
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js", :type => "text/javascript"}


.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-8
    %h2 Quote
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/dashboard"} Dashboard
      %li.breadcrumb-item.active
        %strong List View
  .col-lg-4
    .clearfix-big
    .float-right
      %a.btn.btn-primary.mr-3{href: '/admin/quotes/new'}
        %i.fa.fa-plus
        Add Quote

.wrapper.wrapper-content
  - if flash.present?
    .row
      .col-lg-12
        - flash.each do |name, msg|
          = content_tag :div, msg, class: "alert alert-info"

  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Filter
          .ibox-tools
            %a.collapse-link#filter-quote
              %i.fa.fa-chevron-up
        .ibox-content.filter-quote
          = render 'filter'

  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Quoting Table
          .ibox-tools
            %a.collapse-link#index-quotes
              %i.fa.fa-chevron-up


        .ibox-content.index-quotes
          .table-responsive
            %table.table.table-bordered.table-hover#quote_dt
              %thead
                %tr
                  %th{width: "8%"} ID
                  %th Customer
                  %th Required Date
                  %th Date Quote
                  %th Status
                  %th Salesperson
                  %th Tax
                  %th Total
                  %th Sub Total
              %tbody
                - @quotes.each do |quote|
                  %tr
                    %td
                      %a{href: "/admin/quotes/#{quote.id}"}
                        = "Q - #{quote.id}"
                    %td
                      - if quote.customer_id.present?
                        - if quote.customer.name.present?
                          = quote.customer.name
                        - else
                          = quote.customer_id
                      - else
                        = "NA"
                    %td= quote.date_required.present? ? format_full_date(quote.date_required) : "NA"
                    %td= quote.quote_date.present? ? format_full_date(quote.quote_date) : "NA"
                    %td= quote.status
                    %td= quote.user_id.present? ? quote.user.email : "---"
                    %td= quote.tax_id.present? ? "#{quote.tax.code} - #{quote.tax_percentage}%" : "---"
                    %td= quote.total
                    %td= quote.subtotal


:javascript
  $( document ).ready(function() {

    $('#quote_dt').dataTable({
      searching: false,
      paging: true,
      info: true,
      "order": [[ 0, "desc" ]],
      dom: 'Bfrtip',
      buttons: [
          'copy', 'csv', 'excel', 'print', {
                extend: 'pdf',
                orientation: 'landscape'
            }
      ]
    });

    $('.collapse-link').on('click', function (e) {
      var id = $(this).attr('id');
      $("."+id).slideToggle(200);
    });
  });

app/views/admin/quotes/new.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2 Create Quote
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{:href => "/admin/quotes"} List View
      %li.breadcrumb-item.active
        %strong New
  .col-lg-2

.wrapper.wrapper-content
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Quote Form
          .ibox-tools
            %a.collapse-link#quote-form
              %i.fa.fa-chevron-up

        .ibox-content.quote-form
          = render "form"

:javascript
  $( document ).ready(function() {
    $('.collapse-link').on('click', function (e) {
      var id = $(this).attr('id');
      $("."+id).slideToggle(200);
    });
  });